select avg(height) from heroes_information;

select Name from heroes_information
where height  = (select max(height) from heroes_information);

select Name from heroes_information
where weight = (select max(weight) from heroes_information);

select gender, count(*)  from heroes_information group by gender;

select alignment, count(*)  from heroes_information group by alignment;

select publisher from heroes_information
group by publisher order by count(publisher) desc limit 5;

select "Hair color"  from heroes_information
group by "Hair color"  order by count("Hair color") desc limit 3;

select "Eye color"  from heroes_information
group by "Eye color"  order by count("Eye color") desc limit 1;

create table publishers
(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name 	   varchar(100) UNIQUE,
created_at TIMESTAMP default now() NOT NULL
);

insert into publishers(name) select distinct publisher from heroes_information;

alter table heroes_information
add column  publisher_id INTEGER REFERENCES Publishers(id);

update heroes_information set publisher_id = publishers.id from publishers where heroes_information.publisher = publishers.name;

alter table heroes_information drop column publisher;

select publishers.id from heroes_information group by publisher_id order by count(publisher_id) desc limit 5;

