CREATE TABLE IF NOT EXISTS accounts
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid  varchar(50) not null,
    iban varchar(100) not null,
    balance DOUBLE precision not null,
    person_id INTEGER REFERENCES persons(id)
);